[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .output/server/index.mjs"

[variables]
NODE_VERSION = "20"
